/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import Logica.LugarE;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

/**
 *
 * @author Clint
 */
public class Estacionamiento extends javax.swing.JFrame {

    /**
     * Creates new form Estacionamiento
     */
    Map<Integer, String> lugar = new HashMap<Integer, String>();
    int u;
    public Estacionamiento() {
        initComponents();
        
    }

    public void mostrar(Map<Integer, String> lugar2){
        lugar =lugar2;
    }
    
    public void ocupar(){
        Iterator it = lugar.keySet().iterator();
        while(it.hasNext()){
            Integer key = (Integer) it.next();
                if(key==1){
                    U1.setBackground(Color.RED);
                }
                if(key==2){
                    U2.setBackground(Color.RED);
                }
                if(key==3){
                    U3.setBackground(Color.RED);
                }
                if(key==4){
                    U4.setBackground(Color.RED);
                }
                if(key==5){
                    U5.setBackground(Color.RED);
                }
                if(key==6){
                    U6.setBackground(Color.RED);
                }
                if(key==7){
                    U7.setBackground(Color.RED);
                }
                if(key==8){
                    U8.setBackground(Color.RED);
                }
                if(key==9){
                    U9.setBackground(Color.RED);
                }
                if(key==10){
                    U10.setBackground(Color.RED);
                }
                if(key==11){
                    U11.setBackground(Color.RED);
                }
                if(key==12){
                    U12.setBackground(Color.RED);
                }
                if(key==13){
                    U13.setBackground(Color.RED);
                }
                if(key==14){
                    U14.setBackground(Color.RED);
                }
                if(key==15){
                    U15.setBackground(Color.RED);
                }
                if(key==16){
                    U16.setBackground(Color.RED);
                }
                if(key==17){
                    U17.setBackground(Color.RED);
                }
                if(key==18){
                    U18.setBackground(Color.RED);
                }
                if(key==19){
                    U19.setBackground(Color.RED);
                }
                if(key==20){
                    U20.setBackground(Color.RED);
                }
                if(key==21){
                    U21.setBackground(Color.RED);
                }
                if(key==22){
                    U22.setBackground(Color.RED);
                }
                if(key==23){
                    U23.setBackground(Color.RED);
                }
                if(key==24){
                    U24.setBackground(Color.RED);
                }
                if(key==25){
                    U25.setBackground(Color.RED);
                }
                if(key==26){
                    U26.setBackground(Color.RED);
                }
                if(key==27){
                    U27.setBackground(Color.RED);
                }
                if(key==28){
                    U28.setBackground(Color.RED);
                }
                if(key==29){
                    U29.setBackground(Color.RED);
                }
                if(key==30){
                    U30.setBackground(Color.RED);
                }
             
           
        }       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        U1 = new javax.swing.JButton();
        U2 = new javax.swing.JButton();
        U3 = new javax.swing.JButton();
        U4 = new javax.swing.JButton();
        U5 = new javax.swing.JButton();
        U6 = new javax.swing.JButton();
        U7 = new javax.swing.JButton();
        U8 = new javax.swing.JButton();
        U9 = new javax.swing.JButton();
        U10 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        U11 = new javax.swing.JButton();
        U12 = new javax.swing.JButton();
        U13 = new javax.swing.JButton();
        U14 = new javax.swing.JButton();
        U15 = new javax.swing.JButton();
        U16 = new javax.swing.JButton();
        U17 = new javax.swing.JButton();
        U18 = new javax.swing.JButton();
        U19 = new javax.swing.JButton();
        U20 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        U21 = new javax.swing.JButton();
        U22 = new javax.swing.JButton();
        U23 = new javax.swing.JButton();
        U24 = new javax.swing.JButton();
        U25 = new javax.swing.JButton();
        U26 = new javax.swing.JButton();
        U27 = new javax.swing.JButton();
        U28 = new javax.swing.JButton();
        U29 = new javax.swing.JButton();
        U30 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(767, 422));
        setMinimumSize(new java.awt.Dimension(767, 422));
        setPreferredSize(new java.awt.Dimension(767, 422));
        getContentPane().setLayout(null);

        jLabel1.setText("PISO 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 250, 90, 30);

        U1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U1.setText("1");
        U1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U1ActionPerformed(evt);
            }
        });
        getContentPane().add(U1);
        U1.setBounds(30, 320, 40, 21);

        U2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U2.setText("2");
        getContentPane().add(U2);
        U2.setBounds(90, 320, 50, 21);

        U3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U3.setText("3");
        getContentPane().add(U3);
        U3.setBounds(150, 320, 50, 21);

        U4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U4.setText("4");
        getContentPane().add(U4);
        U4.setBounds(210, 320, 50, 21);

        U5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U5.setText("5");
        getContentPane().add(U5);
        U5.setBounds(270, 320, 50, 21);

        U6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U6.setText("6");
        getContentPane().add(U6);
        U6.setBounds(330, 320, 50, 21);

        U7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U7.setText("7");
        getContentPane().add(U7);
        U7.setBounds(390, 320, 40, 21);

        U8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U8.setText("8");
        U8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U8ActionPerformed(evt);
            }
        });
        getContentPane().add(U8);
        U8.setBounds(450, 320, 40, 21);

        U9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U9.setText("9");
        getContentPane().add(U9);
        U9.setBounds(510, 320, 50, 21);

        U10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U10.setText("10");
        getContentPane().add(U10);
        U10.setBounds(570, 320, 50, 21);

        jLabel4.setText("PISO 2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 80, 30);

        U11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U11.setText("11");
        getContentPane().add(U11);
        U11.setBounds(23, 190, 50, 21);

        U12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U12.setText("12");
        getContentPane().add(U12);
        U12.setBounds(90, 190, 50, 21);

        U13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U13.setText("13");
        getContentPane().add(U13);
        U13.setBounds(150, 190, 50, 21);

        U14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U14.setText("14");
        getContentPane().add(U14);
        U14.setBounds(210, 190, 48, 21);

        U15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U15.setText("15");
        getContentPane().add(U15);
        U15.setBounds(270, 190, 50, 21);

        U16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U16.setText("16");
        getContentPane().add(U16);
        U16.setBounds(330, 190, 50, 21);

        U17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U17.setText("17");
        getContentPane().add(U17);
        U17.setBounds(390, 190, 50, 21);

        U18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U18.setText("18");
        getContentPane().add(U18);
        U18.setBounds(450, 190, 50, 21);

        U19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U19.setText("19");
        getContentPane().add(U19);
        U19.setBounds(510, 190, 50, 21);

        U20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U20.setText("20");
        getContentPane().add(U20);
        U20.setBounds(570, 190, 50, 21);

        jLabel2.setText("PISO 3");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 20, 70, 30);

        U21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U21.setText("21");
        getContentPane().add(U21);
        U21.setBounds(30, 70, 50, 21);

        U22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U22.setText("22");
        getContentPane().add(U22);
        U22.setBounds(90, 70, 50, 21);

        U23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U23.setText("23");
        getContentPane().add(U23);
        U23.setBounds(150, 70, 50, 21);

        U24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U24.setText("24");
        getContentPane().add(U24);
        U24.setBounds(210, 70, 50, 21);

        U25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U25.setText("25");
        getContentPane().add(U25);
        U25.setBounds(270, 70, 50, 21);

        U26.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U26.setText("26");
        getContentPane().add(U26);
        U26.setBounds(330, 70, 50, 21);

        U27.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U27.setText("27");
        U27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U27ActionPerformed(evt);
            }
        });
        getContentPane().add(U27);
        U27.setBounds(390, 70, 50, 21);

        U28.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U28.setText("28");
        U28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U28ActionPerformed(evt);
            }
        });
        getContentPane().add(U28);
        U28.setBounds(450, 70, 50, 20);

        U29.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U29.setText("29");
        U29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U29ActionPerformed(evt);
            }
        });
        getContentPane().add(U29);
        U29.setBounds(510, 70, 50, 21);

        U30.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U30.setText("30");
        U30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U30ActionPerformed(evt);
            }
        });
        getContentPane().add(U30);
        U30.setBounds(570, 70, 50, 21);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Clint\\Documents\\NetBeansProjects\\estacionamiento\\src\\imagenes\\parqueadero.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 770, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void U8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U8ActionPerformed

    private void U27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U27ActionPerformed

    private void U28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U28ActionPerformed

    private void U29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U29ActionPerformed

    private void U30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U30ActionPerformed

    private void U1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estacionamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton U1;
    private javax.swing.JButton U10;
    private javax.swing.JButton U11;
    private javax.swing.JButton U12;
    private javax.swing.JButton U13;
    private javax.swing.JButton U14;
    private javax.swing.JButton U15;
    private javax.swing.JButton U16;
    private javax.swing.JButton U17;
    private javax.swing.JButton U18;
    private javax.swing.JButton U19;
    private javax.swing.JButton U2;
    private javax.swing.JButton U20;
    private javax.swing.JButton U21;
    private javax.swing.JButton U22;
    private javax.swing.JButton U23;
    private javax.swing.JButton U24;
    private javax.swing.JButton U25;
    private javax.swing.JButton U26;
    private javax.swing.JButton U27;
    private javax.swing.JButton U28;
    private javax.swing.JButton U29;
    private javax.swing.JButton U3;
    private javax.swing.JButton U30;
    private javax.swing.JButton U4;
    private javax.swing.JButton U5;
    private javax.swing.JButton U6;
    private javax.swing.JButton U7;
    private javax.swing.JButton U8;
    private javax.swing.JButton U9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
